### ISSUE TITLE
GB28181.DeviceInfoMgr and WebServiceSDK project is not included.

### ISSUE THREAD

**Issue by mitshan1994** [usecpp/GB28181Platform#1]
I want to compile the solution in VS2017 using vc toolset v141. But I can't find sub-projects **GB28181.DeviceInfoMgr** and **WebServiceSDK**. Can you supply these two projects in the repo or leave a reference to these two projects so the solution gets self-completed.

**Comment by crazybber** [comment]
WebServiceSDK is not necessary ,DeviceInfoMgr maybe just naming issue.
i wil updates for it.
